# Generated by Django 3.0.8 on 2020-08-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('created_date', models.DateTimeField(blank=True)),
                ('updated_date', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'ans_subscribe',
            },
        ),
    ]
