# Generated by Django 3.0.8 on 2020-08-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0002_subscribemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeModel',
        ),
    ]
